### ISSUE TITLE
Strange .vscode-test directory taking up 250MB

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [josa42/vscode-markdown-table-formatter#5]
I just noticed that this extension was weighing in at a considerable size of 250MB. Almost all of that from a directory ```.vscode-test``` that appears to contain a complete installation of vscode.

This may be something I caused without noticing, but maybe others could check if it happens with their installation as well–250MB is sizeable enough to be annoying.

Here's ```~/.vscode/extensions/josa.markdown-table-formatter-0.2.2```

```
4.0K	.editorconfig
247M	.vscode-test
    1.7M    .vscode-test/Visual Studio Code.app/Contents/_CodeSignature/
    178M   .vscode-test/Visual Studio Code.app/Contents/Frameworks/
    44K	.vscode-test/Visual Studio Code.app/Contents/MacOS/
    68M	.vscode-test/Visual Studio Code.app/Contents/Resources/
4.0K	.vsixmanifest
4.0K	CHANGELOG.md
12K	docs
4.0K	LICENSE.md
72K	node_modules
8.0K	out
4.0K	package.json
4.0K	README.md
```

**Comment by josa42** [comment]
Fixed in `0.2.3`. Thanks for reporting!
