### ISSUE TITLE
Bug: Incorrect formatting of table

### ISSUE THREAD

**Issue by coliff** [josa42/vscode-markdown-table-formatter#6]
If I format the following table:

```
| Supported in following Version   | Minimum Version Supported |
|------------------------------------------|---------------------------|
|                                          | Win32/64 (inc. Windows 7, Windows 8 Pro)   |
|                                          | Android 4.1                          |
```

then the output is:

```
| Supported in following Version           | Minimum Version Supported |
|------------------------------------------|---------------------------|
| Win32/64 (inc. Windows 7, Windows 8 Pro) |                           |
| Android 4.1                              |                           |
```

The content of the second column is incorrectly moved to the first. The first columns should be empty. I hope you can release a fix for this issue as otherwise this extension is great.

**Comment by faustinoaq** [comment]
I have the same issue, I see this extension is very simple. The bug could be solved changing/fixing `TABLE_EXP `.

In some place :point_down: is the bug :sweat_smile: 

```js
const TABLE_EXP = /((?:(?:[^\n]*?\|[^\n]*)\ *)?(?:\r?\n|^))((?:\|\ *(?::?-+:?|::)\ *|\|?(?:\ *(?::?-+:?|::)\ *\|)+)(?:\ *(?::?-+:?|::)\ *)?\ *\r?\n)((?:(?:[^\n]*?\|[^\n]*)\ *(?:\r?\n|$))+)/g;
```

Reference: [extract-tables.ts#L1](https://github.com/josa42/vscode-markdown-table-formatter/blob/master/src/utils/extract-tables.ts#L1)

@coliff  Thanks for this extension!

**Comment by coliff** [comment]
@josa42 would it be possible to release an update with a fix for this issue?

**Comment by jcrben** [comment]
https://github.com/fcrespo82/vscode-markdown-table-formatter might be better
