### ISSUE TITLE
indented tables are not formatted

### ISSUE THREAD

**Issue by parkej4** [josa42/vscode-markdown-table-formatter#8]
The plugin doesn't format tables that are indented.  For example, tables

```
|foo1|bar1|
|-|-|
|a|b|
|c|d|

    |foo2|bar2|
    |-|-|
    |a|b|
    |c|d|
```
are formatted to this..

```
| foo1 | bar1 |
|------|------|
| a    | b    |
| c    | d    |

    |foo2|bar2|
    |-|-|
    |a|b|
    |c|d|
```

The first table is formatted, but the second, indented table shows no change.

**Comment by josa42** [comment]
This works as intended. Tables cannot be indented. In the provided example, the second "table" would be treated as code block, which should not be formatted.

![image](https://user-images.githubusercontent.com/423234/62498952-3ff42400-b7e1-11e9-8a36-2ff388cc92ba.png)
